# $Id$ -*- Makefile -*-
# Create DDD in a separate binary directory.

# Usage: In the DDD directory, run `make -f Makefile.bin TARGET' (or
# link `Makefile.bin' to `Makefile').  All targets will be made in an
# architecture-dependent binary directory named `../`uname'/ddd'.

# Make target in architecture-dependent binary directory
MAKE_IT = \
	@dir="../`sh ../config.guess`/ddd"; \
	test -d $$dir || mkdir $$dir; \
        cd $$dir; \
	test -f Makefile || ( cd ..; ../configure ); \
	$(MAKE) $@

# Default target
all:	FORCE
	$(MAKE_IT)

# Override implicit rules
%.o: %.C
	$(MAKE_IT)
%.o: %.c
	$(MAKE_IT)

# Sun CC has phony targets like `.INIT' or `.DONE'...
.%: FORCE
	@:

# Catch-all rule
%: FORCE
	$(MAKE_IT)

FORCE: ;
