#! /bin/sh
# make all lex/yacc declarations static

# Copyright (C) 1995 Technische Universitaet Braunschweig, Germany.
# Written by Andreas Zeller <zeller@gnu.org>.
# 
# This file is part of DDD.
# 
# DDD is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# DDD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with DDD -- see the file COPYING.
# If not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# 
# DDD is the data display debugger.
# For details, see the DDD World-Wide-Web page, 
# `http://www.gnu.org/software/ddd/',
# or send a mail to the DDD developers <ddd@gnu.org>.

sed '
s/^[a-zA-Z_][a-zA-Z_]*[ 	\*][ 	\*]*yy[a-zA-Z_]/static &/
s/^int$/static &/
s/^YY_DECL/static &/
s/^static return/return/
s/^static static/static/g
\/{/s/^static struct/struct/
\/=/s/^struct/static &/
\/::/s/^static //
s/^static \([a-zA-Z_]*:\)/\1/
s/extern \([a-zA-Z_]\)/static \1/
s/extern "C" \([a-zA-Z_]* yy\)/static \1/
s/static struct yy_buffer_state/struct yy_buffer_state/
' $*
