#! /bin/sh
# make all lex/yacc declarations static

# Copyright (C) 1995 Technische Universitaet Braunschweig, Germany.
# Written by Andreas Zeller <zeller@ips.cs.tu-bs.de>.
# 
# This file is part of the ICE Library.
# 
# The ICE Library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# The ICE Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Library General Public License for more details.
# 
# You should have received a copy of the GNU Library General Public
# License along with the ICE Library -- see the file COPYING.LIB.
# If not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# 
# ICE is the incremental configuration engine.
# Contact ice@ips.cs.tu-bs.de for details.

sed '
s/^[a-zA-Z_][a-zA-Z_]*[ 	\*][ 	\*]*yy[a-zA-Z_]/static &/
s/^int$/static &/
s/^YY_DECL/static &/
s/^static return/return/
s/^static static/static/g
\/{/s/^static struct/struct/
\/=/s/^struct/static &/
\/::/s/^static //
s/^static \([a-zA-Z_]*:\)/\1/
s/extern \([a-zA-Z_]\)/static \1/
s/extern "C" \([a-zA-Z_]* yy\)/static \1/
s/static struct yy_buffer_state/struct yy_buffer_state/
' $*
