name: DDD CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo ./.github/apt-deps.sh
    - name: CVSMake
      run: ./CVSMake
    - name: configure
      run: ./configure
    - name: make
      run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck

  build-ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo ./.github/apt-deps.sh
    - name: CVSMake
      run: ./CVSMake
    - name: configure
      run: ./configure
    - name: make
      run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
